services:
  
  sniffer:
    build: .
    image: guardian-ebpf:v1
    privileged: true 
    pid: "host"
    environment:
      - TARGET_SOURCE_PATH=/app/targets/leaker.cpp
    volumes:
      - /lib/modules:/lib/modules:ro
      - /usr/src:/usr/src:ro
      - /sys/kernel/debug:/sys/kernel/debug:rw
      - /proc:/proc:ro
      - ./data:/app/data
      - ./targets:/app/targets
    command: main.py --duration 3600
    ports:
      - "8000:8000" 

  agent:
    image: guardian-ebpf:v1
    environment:
      - OLLAMA_HOST=http://192.168.5.2:11434
      - TARGET_SOURCE_PATH=/app/targets/leaker.cpp
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./data:/app/data
      - ./targets:/app/targets
      - ./src:/app/src
    command: src/agent/webhook_receiver.py
    ports:
      - "5001:5001"

  dashboard:
    image: guardian-ebpf:v1
    environment:
      - TARGET_SOURCE_PATH=/app/targets/leaker.cpp
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    command: -m streamlit run src/dashboard/app.py --server.port=8501 --server.address=0.0.0.0

  prometheus:
      image: prom/prometheus:latest
      volumes:
        - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
        - ./monitoring/alert_rules.yml:/etc/prometheus/alert_rules.yml
      ports:
        - "9090:9090"
      command:
        - "--config.file=/etc/prometheus/prometheus.yml"
  alertmanager:
    image: prom/alertmanager:latest
    volumes:
      - ./monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"